#!/bin/bash

# List of protected branch patterns
protected_patterns=("*exercise-solutions" "master")

# Function to check if the branch name matches any pattern
branch_matches() {
    local branch=$1
    for pattern in "${protected_patterns[@]}"; do
        if [[ $branch == $pattern ]]; then
            return 0
        fi
    done
    return 1
}

# Get the name of the current branch
branch_name=$(git symbolic-ref --short HEAD)

# Check if the branch name matches any of the protected patterns
if branch_matches "$branch_name"; then
    echo "You are not allowed to commit directly to the ${branch_name} branch."
    exit 1
fi

echo "Pre-commit checks passed."
